import { cn } from '@repo/lib/utils';
import './globals.css';
import '@repo/ui/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Poppins } from 'next/font/google';
import { auth } from '../auth';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from 'sonner';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'], // You can specify other weights if needed
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn(inter.className, poppins.className)}>
          <Toaster className="text-black" richColors />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
