name: Cleanup Old Messages

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run cleanup script
        run: node cleanupMessages.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # Ensure you have this in your GitHub Secrets
